import { makeStyles, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  userAvatar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  userAvatarTextContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
  },
  peopleList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  peopleListItem: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "4px",
    borderRadius: "8px",
    ":hover": {
      background: tokens.colorNeutralBackground3Hover,
      transition: "background 0.5s",
    },
  },
  peopleListBadge: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  centered: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  sidebarContent: {
    display: "flex",
    flexDirection: "column",
    width: "280px",
    gap: "16px",
    marginBottom: "16px",
    color: tokens.colorNeutralForeground1,
  },
  link: {
    color: tokens.colorNeutralForeground1,
    textDecoration: "none",
  },
  icon: {
    marginRight: "2px",
    fontSize: "16px",
  },
  workstyleViewContainer: {
    position: "relative",
    backgroundColor: "none",
    padding: "16px 0px",
    display: "flex",
    flexDirection: "column",
    alignContent: "start",
    gap: "4px",
  },
  workstyleContainer: {
    position: "relative",
    backgroundColor: tokens.colorNeutralBackground1,
    padding: "12px",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: "8px",
  },
  flexRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "start",
    gap: "4px",
    flexWrap: "wrap",
  },
  workstyleTabHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "8px",
  },
  workstyleButtons: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "8px",
  },
  workstyleHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    borderRadius: "8px",
    padding: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  divider: {
    marginTop: "12px",
    marginBottom: "12px",
    opacity: 0.3,
    width: "100%",
  },
  keyword: {
    padding: "8px 12px",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: "48px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: tokens.colorNeutralBackground1,
  },
  keywordsContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
    margin: "20px 0px",
  },
  config: {
    height: "100%",
    width: "100%",
    display: "flex",
    alignItems: "start",
    justifyContent: "center",
    flexDirection: "column",
    gap: "16px",
    padding: "16px 0",
    background: "none",
  },
});
